<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Orders_model extends CI_Model
{

    public $table = 'orders';
    public $id = 'id';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select('select orders.id, concat(address.first_name, " ", address.last_name) as name, orders.tglinput, concat(address.address, ", ", address.district, ", ", address.regency, " - ", address.province, " ", address.post_code) as alamat, orders.gtotal')
        ->from('orders, address, users')
        ->where('orders.addrid = address.id and orders.mbrid = u.id')
        ->order_by('orders.id', 'ASC');
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
        $this->db->or_like('mbrid', $q);
        $this->db->or_like('total', $q);
        $this->db->or_like('payment', $q);
        $this->db->or_like('note', $q);
        $this->db->or_like('delivery', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->select('select orders.id, concat(address.first_name, " ", address.last_name) as name, orders.tglinput, concat(address.address, ", ", address.district, ", ", address.regency, " - ", address.province, " ", address.post_code) as alamat, orders.gtotal');
        $this->db->from('orders');
        $this->db->join('address', 'orders.addrid = address.id');
        $this->db->join('users', 'orders.mbrid = users.id');

        // $this->db->order_by($this->id, $this->order);
        $this->db->or_like('orders.id', $q);

        $this->db->or_like('orders.mbrid', $q);
        $this->db->or_like('orders.total', $q);
        $this->db->or_like('orders.payment', $q);
        $this->db->or_like('orders.note', $q);
        $this->db->or_like('orders.delivery', $q);
        $this->db->order_by('orders.id', 'ASC');
        $this->db->limit($limit, $start);
        return $this->db->get()->result(); //$this->table
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Orders_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-05-05 15:06:21 */
/* http://harviacode.com */